server:
  port: 9004 #服务访问端口号
spring:
  application:
    name: tensquare-article #指定服务名
  datasource: #数据库连接四大属性
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
  data:  #配置MongoDB
    mongodb: #默认端口号不用配置
      host: 192.168.200.128
      database: commentdb
  redis: #默认端口号不用配置
    host: 192.168.200.128
  rabbitmq:
    host: 192.168.200.128



# Mybatis-Plus 配置
mybatis-plus:
  #  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.Tony.article.pojo
  global-config:
    id-type: 1  #0:数据库ID自增  ； 1:用户输入id  #因为使用雪花算法
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true
